### ISSUE TITLE
The link to the DI-engine code for DT looks wrong..

### ISSUE THREAD

**Issue by yuchenlin** [opendilab/awesome-decision-transformer#1]
Hi there,

Thank you for your great reading list for DT. The link under NeurIPS 2021 for DI-engine's DT is the same as the official repo of the authors of DT. Maybe it's a typo? 

https://github.com/opendilab/awesome-decision-transformer/blob/main/README.md#neurips-2021

**Comment by YinminZhang** [comment]
Thanks for your friendly reminder! Please check out this [commit](https://github.com/opendilab/awesome-decision-transformer/commit/a41c04f6b780b0412879bc54ad4e38aa0646dcca), which has been fixed.
