### ISSUE TITLE
Papers might be meaningful to be included

### ISSUE THREAD

**Issue by elicassion** [opendilab/awesome-decision-transformer#2]
Hi OpenDILab,

I want to share our published papers that might be meaningful to be included:

- StARformer: Transformer with State-Action-Reward Representations for Visual Reinforcement Learning at ECCV'22 [https://arxiv.org/abs/2110.06206](https://arxiv.org/abs/2110.06206)

- StARformer: Transformer with State-Action-Reward Representations for Robot Learning at T-PAMI [https://ieeexplore.ieee.org/document/9878209](https://ieeexplore.ieee.org/document/9878209)

Thanks and regards,
Jinghuan

**Comment by YinminZhang** [comment]
Thank you for sharing published papers with us. They indeed seem meaningful and relevant to be included.

We appreciate your contribution and will consider adding these papers to future updates. (Index is very cute!)
